=== streamster/streamster/packages/usgs/src/meta/usgsInstantaneousSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Instantaneous",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "declaredType": { "type": "string" },
    "scope": { "type": "string" },
    "value": {
      "type": "object",
      "properties": {
        "queryInfo": {
          "type": "object",
          "properties": {
            "queryURL": { "type": "string" },
            "criteria": {
              "type": "object",
              "properties": {
                "locationParam": { "type": "string" },
                "variableParam": { "type": "string" },
                "parameter": { "type": "array", "items": {} }
              }
            },
            "note": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "value": { "type": "string" },
                  "title": { "type": "string" }
                },
                "required": ["value", "title"]
              }
            }
          }
        },
        "timeSeries": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "sourceInfo": {
                "type": "object",
                "properties": {
                  "siteName": { "type": "string" },
                  "siteCode": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "value": { "type": "string" },
                        "network": { "type": "string" },
                        "agencyCode": { "type": "string" }
                      }
                    }
                  },
                  "timeZoneInfo": {
                    "type": "object",
                    "properties": {
                      "defaultTimeZone": {
                        "type": "object",
                        "properties": {
                          "zoneOffset": { "type": "string" },
                          "zoneAbbreviation": { "type": "string" }
                        }
                      },
                      "daylightSavingsTimeZone": {
                        "type": "object",
                        "properties": {
                          "zoneOffset": { "type": "string" },
                          "zoneAbbreviation": { "type": "string" }
                        }
                      },
                      "siteUsesDaylightSavingsTime": { "type": "boolean" }
                    }
                  },
                  "geoLocation": {
                    "type": "object",
                    "properties": {
                      "geogLocation": {
                        "type": "object",
                        "properties": {
                          "srs": { "type": "string" },
                          "latitude": { "type": "number" },
                          "longitude": { "type": "number" }
                        }
                      },
                      "localSiteXY": { "type": "array", "items": {} }
                    }
                  },
                  "note": { "type": "array", "items": {} },
                  "siteType": { "type": "array", "items": {} },
                  "siteProperty": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "value": { "type": "string" },
                        "name": { "type": "string" }
                      },
                      "required": ["value", "name"]
                    }
                  }
                }
              },
              "variable": {
                "type": "object",
                "properties": {
                  "variableCode": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "value": { "type": "string" },
                        "network": { "type": "string" },
                        "vocabulary": { "type": "string" },
                        "variableID": { "type": "number" },
                        "default": { "type": "boolean" }
                      }
                    }
                  },
                  "variableName": { "type": "string" },
                  "variableDescription": { "type": "string" },
                  "valueType": { "type": "string" },
                  "unit": {
                    "type": "object",
                    "properties": { "unitCode": { "type": "string" } }
                  },
                  "options": {
                    "type": "object",
                    "properties": {
                      "option": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "name": { "type": "string" },
                            "optionCode": { "type": "string" }
                          }
                        }
                      }
                    }
                  },
                  "note": { "type": "array", "items": {} },
                  "noDataValue": { "type": "number" },
                  "variableProperty": { "type": "array", "items": {} },
                  "oid": { "type": "string" }
                }
              },
              "values": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "value": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "value": { "type": "string" },
                          "qualifiers": {
                            "type": "array",
                            "items": { "type": "string" }
                          },
                          "dateTime": { "type": "string" }
                        }
                      }
                    },
                    "qualifier": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "qualifierCode": { "type": "string" },
                          "qualifierDescription": { "type": "string" },
                          "qualifierID": { "type": "number" },
                          "network": { "type": "string" },
                          "vocabulary": { "type": "string" }
                        }
                      }
                    },
                    "qualityControlLevel": { "type": "array", "items": {} },
                    "method": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "methodDescription": { "type": "string" },
                          "methodID": { "type": "number" }
                        }
                      }
                    },
                    "source": { "type": "array", "items": {} },
                    "offset": { "type": "array", "items": {} },
                    "sample": { "type": "array", "items": {} },
                    "censorCode": { "type": "array", "items": {} }
                  }
                }
              },
              "name": { "type": "string" }
            }
          }
        }
      }
    },
    "nil": { "type": "boolean" },
    "globalScope": { "type": "boolean" },
    "typeSubstituted": { "type": "boolean" }
  }
}

=== streamster/streamster/packages/usgs/src/Daily/data.json
{
  "name": "ns1:timeSeriesResponseType",
  "declaredType": "org.cuahsi.waterml.TimeSeriesResponseType",
  "scope": "javax.xml.bind.JAXBElement$GlobalScope",
  "value": {
    "queryInfo": {
      "queryURL": "http://waterservices.usgs.gov/nwis/dv/format=json&sites=09361500&startDT=2020-09-01&endDT=2020-09-02&parameterCd=00060&siteStatus=all",
      "criteria": {
        "locationParam": "[ALL:09361500]",
        "variableParam": "[00060]",
        "timeParam": {
          "beginDateTime": "2020-09-01T00:00:00.000",
          "endDateTime": "2020-09-02T00:00:00.000"
        },
        "parameter": []
      },
      "note": [
        { "value": "[ALL:09361500]", "title": "filter:sites" },
        {
          "value": "[mode=RANGE, modifiedSince=null] interval={INTERVAL[2020-09-01T00:00:00.000-04:00/2020-09-02T00:00:00.000-04:00]}",
          "title": "filter:timeRange"
        },
        { "value": "methodIds=[ALL]", "title": "filter:methodId" },
        { "value": "2020-12-07T14:35:58.320Z", "title": "requestDT" },
        {
          "value": "855787f0-3899-11eb-91f9-2cea7f5e5ede",
          "title": "requestId"
        },
        {
          "value": "Provisional data are subject to revision. Go to http://waterdata.usgs.gov/nwis/help/?provisional for more information.",
          "title": "disclaimer"
        },
        { "value": "sdas01", "title": "server" }
      ]
    },
    "timeSeries": [
      {
        "sourceInfo": {
          "siteName": "ANIMAS RIVER AT DURANGO, CO",
          "siteCode": [
            { "value": "09361500", "network": "NWIS", "agencyCode": "USGS" }
          ],
          "timeZoneInfo": {
            "defaultTimeZone": {
              "zoneOffset": "-07:00",
              "zoneAbbreviation": "MST"
            },
            "daylightSavingsTimeZone": {
              "zoneOffset": "-06:00",
              "zoneAbbreviation": "MDT"
            },
            "siteUsesDaylightSavingsTime": true
          },
          "geoLocation": {
            "geogLocation": {
              "srs": "EPSG:4326",
              "latitude": 37.2791688,
              "longitude": -107.8803445
            },
            "localSiteXY": []
          },
          "note": [],
          "siteType": [],
          "siteProperty": [
            { "value": "ST", "name": "siteTypeCd" },
            { "value": "14080104", "name": "hucCd" },
            { "value": "08", "name": "stateCd" },
            { "value": "08067", "name": "countyCd" }
          ]
        },
        "variable": {
          "variableCode": [
            {
              "value": "00060",
              "network": "NWIS",
              "vocabulary": "NWIS:UnitValues",
              "variableID": 45807197,
              "default": true
            }
          ],
          "variableName": "Streamflow, ft&#179;/s",
          "variableDescription": "Discharge, cubic feet per second",
          "valueType": "Derived Value",
          "unit": { "unitCode": "ft3/s" },
          "options": {
            "option": [
              { "value": "Mean", "name": "Statistic", "optionCode": "00003" }
            ]
          },
          "note": [],
          "noDataValue": -999999.0,
          "variableProperty": [],
          "oid": "45807197"
        },
        "values": [
          {
            "value": [
              {
                "value": "174",
                "qualifiers": ["P"],
                "dateTime": "2020-09-01T00:00:00.000"
              },
              {
                "value": "168",
                "qualifiers": ["P"],
                "dateTime": "2020-09-02T00:00:00.000"
              }
            ],
            "qualifier": [
              {
                "qualifierCode": "P",
                "qualifierDescription": "Provisional data subject to revision.",
                "qualifierID": 0,
                "network": "NWIS",
                "vocabulary": "uv_rmk_cd"
              }
            ],
            "qualityControlLevel": [],
            "method": [{ "methodDescription": "", "methodID": 19604 }],
            "source": [],
            "offset": [],
            "sample": [],
            "censorCode": []
          }
        ],
        "name": "USGS:09361500:00060:00003"
      }
    ]
  },
  "nil": false,
  "globalScope": true,
  "typeSubstituted": false
}

=== streamster/streamster/packages/usgs/src/meta/usgsInstantaneousData.json
{"name":"ns1:timeSeriesResponseType","declaredType":"org.cuahsi.waterml.TimeSeriesResponseType","scope":"javax.xml.bind.JAXBElement$GlobalScope","value":{"queryInfo":{"queryURL":"http://waterservices.usgs.gov/nwis/iv/format=json&sites=09361500,09364500&parameterCd=00060,00010&siteStatus=all","criteria":{"locationParam":"[ALL:09361500, ALL:09364500]","variableParam":"[00060, 00010]","parameter":[]},"note":[{"value":"[ALL:09361500, ALL:09364500]","title":"filter:sites"},{"value":"[mode=LATEST, modifiedSince=null]","title":"filter:timeRange"},{"value":"methodIds=[ALL]","title":"filter:methodId"},{"value":"2020-12-08T15:48:52.919Z","title":"requestDT"},{"value":"df381d60-396c-11eb-becb-2cea7f58f5ca","title":"requestId"},{"value":"Provisional data are subject to revision. Go to http://waterdata.usgs.gov/nwis/help/?provisional for more information.","title":"disclaimer"},{"value":"vaas01","title":"server"}]},"timeSeries":[{"sourceInfo":{"siteName":"ANIMAS RIVER AT DURANGO, CO","siteCode":[{"value":"09361500","network":"NWIS","agencyCode":"USGS"}],"timeZoneInfo":{"defaultTimeZone":{"zoneOffset":"-07:00","zoneAbbreviation":"MST"},"daylightSavingsTimeZone":{"zoneOffset":"-06:00","zoneAbbreviation":"MDT"},"siteUsesDaylightSavingsTime":true},"geoLocation":{"geogLocation":{"srs":"EPSG:4326","latitude":37.2791688,"longitude":-107.8803445},"localSiteXY":[]},"note":[],"siteType":[],"siteProperty":[{"value":"ST","name":"siteTypeCd"},{"value":"14080104","name":"hucCd"},{"value":"08","name":"stateCd"},{"value":"08067","name":"countyCd"}]},"variable":{"variableCode":[{"value":"00010","network":"NWIS","vocabulary":"NWIS:UnitValues","variableID":45807042,"default":true}],"variableName":"Temperature, water, &#176;C","variableDescription":"Temperature, water, degrees Celsius","valueType":"Derived Value","unit":{"unitCode":"deg C"},"options":{"option":[{"name":"Statistic","optionCode":"00000"}]},"note":[],"noDataValue":-999999,"variableProperty":[],"oid":"45807042"},"values":[{"value":[{"value":"2.0","qualifiers":["P"],"dateTime":"2020-12-08T08:30:00.000-07:00"}],"qualifier":[{"qualifierCode":"P","qualifierDescription":"Provisional data subject to revision.","qualifierID":0,"network":"NWIS","vocabulary":"uv_rmk_cd"}],"qualityControlLevel":[],"method":[{"methodDescription":"","methodID":212176}],"source":[],"offset":[],"sample":[],"censorCode":[]}],"name":"USGS:09361500:00010:00000"},{"sourceInfo":{"siteName":"ANIMAS RIVER AT DURANGO, CO","siteCode":[{"value":"09361500","network":"NWIS","agencyCode":"USGS"}],"timeZoneInfo":{"defaultTimeZone":{"zoneOffset":"-07:00","zoneAbbreviation":"MST"},"daylightSavingsTimeZone":{"zoneOffset":"-06:00","zoneAbbreviation":"MDT"},"siteUsesDaylightSavingsTime":true},"geoLocation":{"geogLocation":{"srs":"EPSG:4326","latitude":37.2791688,"longitude":-107.8803445},"localSiteXY":[]},"note":[],"siteType":[],"siteProperty":[{"value":"ST","name":"siteTypeCd"},{"value":"14080104","name":"hucCd"},{"value":"08","name":"stateCd"},{"value":"08067","name":"countyCd"}]},"variable":{"variableCode":[{"value":"00060","network":"NWIS","vocabulary":"NWIS:UnitValues","variableID":45807197,"default":true}],"variableName":"Streamflow, ft&#179;/s","variableDescription":"Discharge, cubic feet per second","valueType":"Derived Value","unit":{"unitCode":"ft3/s"},"options":{"option":[{"name":"Statistic","optionCode":"00000"}]},"note":[],"noDataValue":-999999,"variableProperty":[],"oid":"45807197"},"values":[{"value":[{"value":"110","qualifiers":["P"],"dateTime":"2020-12-08T08:30:00.000-07:00"}],"qualifier":[{"qualifierCode":"P","qualifierDescription":"Provisional data subject to revision.","qualifierID":0,"network":"NWIS","vocabulary":"uv_rmk_cd"}],"qualityControlLevel":[],"method":[{"methodDescription":"","methodID":212173}],"source":[],"offset":[],"sample":[],"censorCode":[]}],"name":"USGS:09361500:00060:00000"},{"sourceInfo":{"siteName":"ANIMAS RIVER AT FARMINGTON, NM","siteCode":[{"value":"09364500","network":"NWIS","agencyCode":"USGS"}],"timeZoneInfo":{"defaultTimeZone":{"zoneOffset":"-07:00","zoneAbbreviation":"MST"},"daylightSavingsTimeZone":{"zoneOffset":"-06:00","zoneAbbreviation":"MDT"},"siteUsesDaylightSavingsTime":true},"geoLocation":{"geogLocation":{"srs":"EPSG:4326","latitude":36.7225,"longitude":-108.20175},"localSiteXY":[]},"note":[],"siteType":[],"siteProperty":[{"value":"ST","name":"siteTypeCd"},{"value":"14080104","name":"hucCd"},{"value":"35","name":"stateCd"},{"value":"35045","name":"countyCd"}]},"variable":{"variableCode":[{"value":"00010","network":"NWIS","vocabulary":"NWIS:UnitValues","variableID":45807042,"default":true}],"variableName":"Temperature, water, &#176;C","variableDescription":"Temperature, water, degrees Celsius","valueType":"Derived Value","unit":{"unitCode":"deg C"},"options":{"option":[{"name":"Statistic","optionCode":"00000"}]},"note":[],"noDataValue":-999999,"variableProperty":[],"oid":"45807042"},"values":[{"value":[{"value":"18.3","qualifiers":["P"],"dateTime":"2020-10-08T16:30:00.000-06:00"}],"qualifier":[{"qualifierCode":"P","qualifierDescription":"Provisional data subject to revision.","qualifierID":0,"network":"NWIS","vocabulary":"uv_rmk_cd"}],"qualityControlLevel":[],"method":[{"methodDescription":"","methodID":101516}],"source":[],"offset":[],"sample":[],"censorCode":[]}],"name":"USGS:09364500:00010:00000"},{"sourceInfo":{"siteName":"ANIMAS RIVER AT FARMINGTON, NM","siteCode":[{"value":"09364500","network":"NWIS","agencyCode":"USGS"}],"timeZoneInfo":{"defaultTimeZone":{"zoneOffset":"-07:00","zoneAbbreviation":"MST"},"daylightSavingsTimeZone":{"zoneOffset":"-06:00","zoneAbbreviation":"MDT"},"siteUsesDaylightSavingsTime":true},"geoLocation":{"geogLocation":{"srs":"EPSG:4326","latitude":36.7225,"longitude":-108.20175},"localSiteXY":[]},"note":[],"siteType":[],"siteProperty":[{"value":"ST","name":"siteTypeCd"},{"value":"14080104","name":"hucCd"},{"value":"35","name":"stateCd"},{"value":"35045","name":"countyCd"}]},"variable":{"variableCode":[{"value":"00060","network":"NWIS","vocabulary":"NWIS:UnitValues","variableID":45807197,"default":true}],"variableName":"Streamflow, ft&#179;/s","variableDescription":"Discharge, cubic feet per second","valueType":"Derived Value","unit":{"unitCode":"ft3/s"},"options":{"option":[{"name":"Statistic","optionCode":"00000"}]},"note":[],"noDataValue":-999999,"variableProperty":[],"oid":"45807197"},"values":[{"value":[{"value":"183","qualifiers":["P"],"dateTime":"2020-12-08T08:30:00.000-07:00"}],"qualifier":[{"qualifierCode":"P","qualifierDescription":"Provisional data subject to revision.","qualifierID":0,"network":"NWIS","vocabulary":"uv_rmk_cd"}],"qualityControlLevel":[],"method":[{"methodDescription":"","methodID":101517}],"source":[],"offset":[],"sample":[],"censorCode":[]}],"name":"USGS:09364500:00060:00000"}]},"nil":false,"globalScope":true,"typeSubstituted":false}
